# (PART) General Course Information {-}

# Syllabus {-}

## CHEM 191: Issues in Environmental Chemistry {-}
#### Chemistry, Earth, and Air: A very short introduction {-}

**Instructor:** Dr. Al Fischer, PhD  
**Office Hours:** By appointment at [calendly.com/drfischer](www.calendly.com/drfischer); drop-ins welcome.  (NS 209)  
**Email:** [dfischer@wcu.edu](mailto:dfischer@wcu.edu)
_____
***Chem 191: Chemistry, Earth, and Air*** is a freshman seminar course with an emphasis on atmospheric chemistry.  The course is geared toward anyone with an interest in chemistry, atmospheric science, environmental science, and/or engineering.  Students will learn through a combination of lectures and a semester-long project to construct and deploy Arduino-based atmospheric sensors.  An emphasis will be placed on overarching concepts and problem-solving skills rather than rote minutia.
_____

## Specific Learning Objectives {-}
1. Demonstrate the ability to program using the Arduino IDE.
1. Demonstrate an ability to solder basic electronic components.
1. Demonstrate an ability to design an electronics enclosure.
1. Demonstrate an ability to use Excel for basic data analysis.
4. Demonstrate atmospheric literacy, as outlined below.
5. Understand how the scientific process works, both in theory and in practice.
2. Show preparedness for future college classes, especially those in the sciences and engineering.

## Themes {-}
*These themes are taken verbatim from the [Atmospheric Science Literacy Framework](https://scied.ucar.edu/atmospheric-science-literacy-framework) and will be used as guideposts throughout the semester.*

- Earth has a thin atmosphere that sustains life.
- Energy from the Sun drives atmospheric processes.
- Atmospheric circulation transports matter and energy.
- Earth's atmosphere changes over time and space, giving rise to weather and climate.
- Earth's atmosphere continuously interacts with the other components of the Earth System.
- We seek to understand the past, present, and future behavior of Earth's atmosphere through scientific observation and reasoning.
- Earth's atmosphere and humans are inextricably linked.

## Prerequisites {-}

Students should be comfortable with algebra and basic statistics (i.e. mean and standard deviation).  A familiarity with chemistry and/or experience programming is helpful but not required.

<div style="page-break-after: always;"></div>

## Required Course Materials {-}
The following books are required and are available from the WCU bookstore and most other book sellers. *Additional required reading material will be posted on the Instructor's website and Blackboard.*

- *Air Pollution and Global Warming*, Mark Z. Jacobsen, Cambridge University Press (rental book)
- *Chemistry: A very short introduction*, Peter Atkins, Oxford University Press. (supplemental text, ~$10)
- *The Atmosphere: A very short introduction*, ~~Peter Atkins~~, Oxford University Press. (supplemental text, ~$10)


Additional required materials:  
- A scientific calculator (not on a cell phone).  An acceptable calculator can be purchased for less than $10.  It should have the capability to do exponents and trigonometry.

## Technology {-}

### Technology requirements {-}
Students will need:
- A laptop computer with at least one standard USB-A port or, for computers without a USB-A port (e.g. newer MacBooks), an appropriate adapter.
- The [Arduino integrated development environment (IDE)](https://www.arduino.cc/en/Main/Software) and [Teensyduino](https://www.pjrc.com/teensy/td_download.html) add-on.  These software are freely available from the developers for Mac OSX, Windows, and Linux.

In addition, students will be provided with components to construct an air quality sensor, which they must return in working order at the end of the semester.  Any student wishing to keep their sensor should purchase their own materials ahead of time through [Mouser Electronics](www.mouser.com) (a bill of materials is available by request, total cost is about $100).

### Personal technology use policies {-}

The use of cell phones during lecture is prohibitied; the sparing use of cell phones during workshop/lab sessions is permitted but discouraged. If you must, please use your cell phone outside the classroom.

In an effort to maintain a productive work environment for all students, please refrain from playing music, videos, etc., in the classroom.

## Off-campus Work {-}
Students will occasionally be required to travel off-campus to setup and retrieve data from their sensors.  The round-trip travel distance typically won't be more than 10 miles, although students will be required to sign a waiver before conducting any work off-campus.

<div style="page-break-after: always;"></div>

## Grading {-}

**Conventions:** The grades of A+ (100-97), A (96.9-93), A- (92.9-90), B+ (89.9-87), B (86.9-83), B- (82.9-80), C+ (79.9-77), C (76.9-73), C- (72.9-70), D+ (69.9-67), D (66.9-63), D- (62.9-60) and F (< 60) indicate gradations in quality from Excellent to Failure. Please note that a C- grade is less than satisfactory and may not meet particular program and/or course requirements. Students must be familiar with the class attendance, withdrawal, and drop-add policies and procedures. A percentage breakdown of the final grade is given in the table below.

Category | Weight
--------- | ---------
Participation and Attendance | 10%
Quizzes & Homework | 15%
Lab Assignments | 15%
Midterm Exam (take home) | 15%
Successful Sensor Build (+ return at end of semester) | 20%
Final Exam (technical paper detailing sensor and results from it) | 25%

**Assignment Submissions:** Students will be required to submit assignments electronically and as hard copies throughout the semester.  Each assignment will state how it should be turned in.
- *For electronic assignments:*
     - Each student will be assigned a personal Dropbox folder to which they will submit assignments.  
     - Files should follow the convention ***firstnameLastname_assignmentName.xyz***.
     - Any files not named appropriately, not in the specified format, or submitted elsewhere will either incur point deductions or not be graded.  
     - Electronic assignments are due at 23:59:59 on the due date or will be counted late.
- *For hard-copy assignments:*
     - Students will turn in a paper copy of the assignment either in class or to the instructors office.  
     - Students should complete any worksheets on the worksheet itself and should not reformat the worksheet.  
     - Any hard-copy assignments that are turned in electronically will not be graded.  
     - Hard-copy assignments are due during class on the due date unless otherwise specified.

**Late Work:** Quizzes, homework, and lab assignments will be accepted up to 7 days late with a deduction of 5 points per day; no work will be accepted after 7 days (including weekends).  ***Exams will not be accepted late.***

**Additional Notes:** Tests may be graded by computer software.  Any answers not in the specified format will not be graded. Written work may be checked for plagiarism using computer software.  Plagiarism will NOT be tolerated (specific policies in *Fine Print*, below).

<div style="page-break-after: always;"></div>

## The Fine Print... {-}

### Course Policies {-}

**Classroom Expectations:** The shared learning space of the college classroom is built on respect for each other and each other’s learning. Learning together means our actions can intentionally and unintentionally distract others from their learning goals. As responsible learners who respect the rights of others and vow to minimize avoidable distractions such as: non- academic technology use, coming in late, sleeping, off-topic discussions, doing other homework, eating, etc.

**Attendance:** Attendance to ALL lab periods is mandatory. You must arrive fully prepared and on time (i.e. 5 minutes early) to each lab period. Makeup labs may not be possible. Remember, 10% of your grade is based on attendance and participation. Please email your instructor if you encounter circumstances that absolutely prevent you from making it to lab on time. In the event of inclement weather please check the University website for campus closings; use common sense when attempting to get to campus and notify your instructor if you are unable to make it. Announcements will be made via e-mail if class must be cancelled when the University has not officially closed.

**Composition-Condition Marks:** Proper mastery of the English language will be considered when assessing lab reports. A student whose written work fails to meet acceptable standards will be assigned a composition-condition (CC) mark by the instructor on the final grade report. All undergraduates who receive two CC grades prior to the semester in which they complete 110 hours at WCU are so notified by the registrar and are required to pass English 300 or English 401 before they will be eligible for graduation. This course must be taken within two semesters of receiving the second CC and must be passed with a grade of C (2.0) or better. Students needing assistance with writing are encouraged to get help from WaLC. All written work submitted for this class may be checked with SafeAssign.

**Civil Discourse at Western Carolina:** Consistent with WCU’s core values and our campus creed, the WCU community accepts the freedoms and responsibilities of our shared community. WCU encourages all to clearly express their own views while at the same time seeking to understand the varieties of style, identity, and opinion that are held in any diverse community. In order for us to sustain a learning environment that promotes and values freedom of expression, we have a shared charge to accept personal responsibility for our actions, reactions, and speech, while seeking to learn from the actions, reactions, and speech of others.

<!-- Proper Laboratory Attire: Students must arrive to lab wearing appropriate attire. Students without appropriate attire will be asked to leave and will not be able to complete the activity for the day (and will be counted absent). Students who forget their goggles may “rent” a pair for a cost of 5 points subtracted from their grade.

- Wear goggles at all times (whenever you are in the room).
- Wear closed-toed shoes that fully cover your feet up to the ankle at all times.
- Wear long pants that extend over the top of your shoes at all times.
- Wear a hair tie for long hair.
- Never wear tank tops, sleeveless shirts, shorts, or sandals.

Laboratory Behavior: Never bring food or drink into the laboratory. This includes sealed bottles and items inside backpacks – leave them outside the lab! Do not chew gum, use tobacco products, or apply cosmetics in the lab. Do not place personal items inside fume hoods or where they may come into contact with chemicals. Keep walkways clear of chairs, bookbags, etc. Wash your hands before leaving lab, and never wear gloves or labcoats outside the lab! -->

<!-- Certain chemicals can have severe harmful effects on unborn children. Any student who is pregnant or might have become pregnant and wished to avoid these hazards should notify her TA or instructor before conducting any laboratory work so that proper safety precautions can be taken. -->



### Institutional Policies {-}

**Course Recording and Broadcasting:** Students may make visual or audio recordings (Recording) of any class related content, using any approved recording device (e.g., smart phone, computer, digital recorder, etc.) upon the prior permission of the instructor and subject to the following restriction(s). The Recording, along with the video capture of visible course materials (e.g., visible PowerPoint slides and/or visible lecture notes), shall be limited to the student’s personal, course related, educational use and shall be subject to all applicable copyright laws and institutional policies. The student may not transfer, transmit, or otherwise disseminate the Recording to any third party, including classmates, without the permission of the instructor. Any violation of these restrictions, or any other restriction verbally communicated by the instructor, may subject the student to the provisions of the WCU Academic Integrity Policy, the WCU Code of Student Conduct or both.

**Accommodations for Students with Disabilities:** Western Carolina University is committed to providing equal educational opportunities for students with documented disabilities and/or medical conditions. Students who require accommodations must identify themselves as having a disability and/or medical condition and provide current diagnostic documentation to the Office of Accessibility Resources. Please contact the Office of Accessibility Resources, 135 Killian Annex (next to the One Stop), (828) 227-3886 or by email at accessibility@wcu.edu. Website: http://accessibility.wcu.edu/.

**Academic Integrity Policy and Reporting Process:** This policy addresses academic integrity violations of undergraduate and graduate students. Graduate students should read inside the parenthesis below to identify the appropriate entities in charge of that step of the process.
Students, faculty, staff, and administrators of Western Carolina University strive to achieve the highest standards of scholarship and integrity. Any violation of the Academic Integrity Policy is a serious offense because it threatens the quality of scholarship and undermines the integrity of the community. While academic in scope, any violation of this policy is by nature, a violation of the Code of Student Conduct and will follow the same conduct process (see ArticleVII.B.1.a.). If the charge occurs close to the end of an academic semester or term or in the event of the reasonable need of either party for additional time to gather information timelines may be extended at the discretion of the Department of Student Community Ethics (DSCE).

*General:*
This policy addresses academic integrity violations of undergraduate and graduate students. Students, faculty, staff, and administrators of Western Carolina University strive to achieve the highest standards of scholarship and integrity. Any violation of this policy is a serious offense because it threatens the quality of scholarship and undermines the integrity of the community. Instructors have the right to determine the appropriate academic sanctions for violations of the Academic Integrity Policy within their courses, up to and including a final grade of “F” in the course in which the violation occurs.

*Definitions:*
- ***Cheating*** – Using, or attempting to use, unauthorized materials, information, or study aids in any academic exercise.
- ***Fabrication*** – Creating and/or falsifying information or citation in any academic exercise.
- ***Plagiarism*** – Representing the words or ideas of someone else as one’s own in any academic exercise.
- ***Facilitation*** – Helping or attempting to help someone to commit a violation of the Academic Integrity Policy in any academic exercise (e.g. allowing another person to copy information during an examination).

Undergraduate and Graduate Academic Integrity Process: Additional information is available on the Student Success website under Student Community Ethics: http://www.wcu.edu/experience/dean-of-students/academic-integrity.aspx.

### Student Resources {-}
**Writing and Learning Commons (WaLC):** The Writing and Learning Commons (WaLC), located in BELK 207, writing tutoring and online writing and learning resources for all students. To view schedules and make appointments for any of these services, visit tutoring.wcu.edu or call 828-227-2274.

**Math Tutoring Center:** The Mathematics Tutoring Center (MTC) in Stillwell 455 provides drop-in tutoring for math courses and math-related content across the curriculum. Tutoring is available on a drop-in basis, MTWR 9:00am-9:00pm and Friday 9:00am-5:00pm. For more information, please visit http://mtc.wcu.edu/ or contact us at 828–227–3830.

**Academic Calendar:** This includes dates for all breaks, university closures, final exams, etc. The academic calendar can be found at http://www.wcu.edu/learn/academic-calendar.asp

### Syllabus Updates
This syllabus and the course schedule are subject to revision as needed. Students will be notified of changes and are responsible for adhering to the modifications.
